// flavours.js

const flavours = [
  { name: "Caramel", category: "Sweet" },
  { name: "Honey", category: "Sweet" },
  { name: "Vanilla", category: "Sweet" },
  { name: "Vanillin", category: "Sweet" },
  { name: "Brown Sugar", category: "Sweet" },
  { name: "Molasses", category: "Sweet" },
  { name: "Butter", category: "Sweet" },
  { name: "Sweet", category: "Sweet" },
  { name: "Mapple syrup", category: "Sweet" },
  { name: "Brittle", category: "Sweet" },

  { name: "Citrus", category: "Citrus" },
  { name: "Lemon", category: "Citrus" },
  { name: "Orange", category: "Citrus" },
  { name: "Lime", category: "Citrus" },
  { name: "Grape", category: "Citrus" },
  { name: "Grapefruit", category: "Citrus" },
  
  { name: "Berry", category: "Berries" },
  { name: "Strawberry", category: "Berries" },
  { name: "Blueberry", category: "Berries" },
  { name: "Raspberry", category: "Berries" },
  { name: "Blackberry", category: "Berries" },
  { name: "Berries", category: "Berries" },
  
  { name: "Fruity", category: "Fruity" },
  { name: "Apple", category: "Fruity" },
  { name: "Peach", category: "Fruity" },
  { name: "Pear", category: "Fruity" },
  { name: "Raisin", category: "Fruity" },
  { name: "Prune", category: "Fruity" },
  { name: "Coconut", category: "Fruity" },
  { name: "Cherry", category: "Fruity" },
  { name: "Pomegranate", category: "Fruity" },
  { name: "Pineapple", category: "Fruity" },
  { name: "Dates", category: "Fruity" },
  { name: "Tropical", category: "Fruity" },
  { name: "Plums", category: "Fruity" },
  { name: "Plums", category: "Fruity" },
  { name: "Dried figs", category: "Fruity" },

  { name: "Nutty", category: "Nutty" },
  { name: "Almond", category: "Nutty" },
  { name: "Hazelnut", category: "Nutty" },
  { name: "Peanut", category: "Nutty" },
  { name: "Walnut", category: "Nutty" },
  { name: "Pecan", category: "Nutty" },
  { name: "Para", category: "Nutty" },
  { name: "Pistachio", category: "Nutty" },
  
  { name: "Cocoa", category: "Cocoa" },
  { name: "Chocolate", category: "Cocoa" },
  { name: "Dark chocolate", category: "Cocoa" },
  { name: "White chocolate", category: "Cocoa" },
  { name: "Milk chocolate", category: "Cocoa" },


  { name: "Floral", category: "Floral" },
  { name: "Jasmine", category: "Floral" },
  { name: "Lavender", category: "Floral" },
  { name: "Rose", category: "Floral" },
  { name: "Chamomile", category: "Floral" },
  { name: "Tea", category: "Floral" },
  { name: "Black tea", category: "Floral" },
  { name: "Green tea", category: "Floral" },

  { name: "Spicy", category: "Spicy" },
  { name: "Cinnamon", category: "Spicy" },
  { name: "Clove", category: "Spicy" },
  { name: "Nutmeg", category: "Spicy" },
  { name: "Pepper", category: "Spicy" },
  { name: "Anise", category: "Spicy" },
  { name: "Pungent", category: "Spicy" },
  { name: "Bread spice", category: "Spicy" },

  { name: "Herbal", category: "Herbal" },
  { name: "Mint", category: "Herbal" },
  { name: "Sage", category: "Herbal" },
  { name: "Thyme", category: "Herbal" },
  { name: "Vegetal", category: "Herbal" },
  { name: "Tomato", category: "Herbal" },
  { name: "Green Pepper", category: "Herbal" },
  { name: "Bean", category: "Herbal" },
  { name: "Olive", category: "Herbal" },
  { name: "Bison grass", category: "Herbal" },

  { name: "Earthy", category: "Earthy" },
  { name: "Mushroom", category: "Earthy" },
  { name: "Forest Floor", category: "Earthy" },
  { name: "Wood", category: "Earthy" },
  { name: "Paper", category: "Earthy" },

  { name: "Roasted", category: "Roasted" },
  { name: "Smoky", category: "Roasted" },
  { name: "Tobacco", category: "Roasted" },
  { name: "Burnt Sugar", category: "Roasted" },
  { name: "Roasted Almond", category: "Roasted" },
  { name: "Coal", category: "Roasted" },
  { name: "Ashy", category: "Roasted" },
  { name: "Acrid", category: "Roasted" },

  { name: "Grain", category: "Cereal" },
  { name: "Barley", category: "Cereal" },
  { name: "Malt", category: "Cereal" },

  { name: "Wine", category: "Fermented" },
  { name: "Whiskey", category: "Fermented" },
  { name: "Fermented", category: "Fermented" },
  { name: "Overripe", category: "Fermented" },
];

export default flavours;
